apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whitehelmet-bribrot

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: backend-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: bribrot
      - op: replace
        path: /data/CORS_ORIGINS
        value: '["https://bribrot.whitehelmet.example.com"]'
