"""add multi-tenant tables

Revision ID: 7bac4a8a6500
Revises: 93be113401bf
Create Date: 2026-04-26 10:48:57.460621
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '7bac4a8a6500'
down_revision: Union[str, None] = '93be113401bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_org_memberships_org_id', table_name='org_memberships')
    op.drop_index('ix_org_memberships_user_id', table_name='org_memberships')
    op.drop_table('org_memberships')
    op.add_column('organizations', sa.Column('type', sa.String(length=10), nullable=False))
    op.alter_column('organizations', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('organizations', 'parent_org_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_index('ix_organizations_external_id', table_name='organizations')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.drop_constraint('organizations_parent_org_id_fkey', 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'slug')
    op.drop_column('organizations', 'is_active')
    op.drop_column('organizations', 'external_id')
    op.drop_column('uploaded_files', 'folder_name')
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('org_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_column('users', 'org_id')
    op.drop_column('users', 'role')
    op.add_column('uploaded_files', sa.Column('folder_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_foreign_key('organizations_parent_org_id_fkey', 'organizations', 'organizations', ['parent_org_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_index('ix_organizations_external_id', 'organizations', ['external_id'], unique=False)
    op.alter_column('organizations', 'parent_org_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('organizations', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('organizations', 'type')
    op.create_table('org_memberships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('system_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='org_memberships_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='org_memberships_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='org_memberships_pkey'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_user_org')
    )
    op.create_index('ix_org_memberships_user_id', 'org_memberships', ['user_id'], unique=False)
    op.create_index('ix_org_memberships_org_id', 'org_memberships', ['org_id'], unique=False)
    # ### end Alembic commands ###
