"""add password_hash to users

Revision ID: 93be113401bf
Revises: bf1ed8129b07
Create Date: 2026-04-20 16:08:42.670309
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '93be113401bf'
down_revision: Union[str, None] = 'bf1ed8129b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
